CREATE TABLE permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id text,
    name TEXT,
    status TEXT,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    eddie_permission_id TEXT,
    eddie_data_need_id text,
    eddie_connector_identifier text,
    eddie_connector_country text,
    meter_resource_id text,
    permission_type TEXT
);

CREATE TABLE time_series_list (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_id BIGINT REFERENCES permission(id),
    temporal_resolution TEXT,
    unit TEXT
);

CREATE TABLE time_series (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time_series_list_id BIGINT REFERENCES time_series_list(id),
    value DOUBLE PRECISION,
    timestamp TIMESTAMP(6) WITH TIME ZONE
);
